<?php
/**
 * options.php
 *
 * @author           Daniele De Vito
 * @copyright        2015 Daniele De Vito
 * @license        GPL-2.0+
 */

$page_slug   = 'tbsc-settings';
$option_name = 'tbsc_settings';
return array(
	// Be sure to do a search and replace when changing any of these values.
	'main_settings'    => array(
		'heading'      => 'Custom Site Options',
		'menu_title'   => 'Site Options',
		'page_slug'    => $page_slug,
		'dashicon'     => plugins_url( 'tbsc-options/images/menu-icon.png' ),
		'option_group' => $option_name . '_group',
		'option_name'  => $option_name,
		'views'        => array(
			'text_small'  => 'text-small.php',
			'text_medium' => 'text-medium.php',
			'text_large'  => 'text-large.php',
			'text_area'   => 'text-area.php',
			'checkbox'    => 'checkbox.php',
			'radio'       => 'radio.php',
			'options'     => 'options.php',
			'editor'      => 'editor.php',
			'media'       => 'file-upload.php',
		),
	),
	'metabox_sections' => array(

		'contact_bar' => array(
			'args'   => array(
				'id'        => 'contact_bar',
				'title'     => 'Contact Bar',
				'desc'      => 'Complete at least all required fields.',
				'page_slug' => $page_slug,
			),
			'fields' => array(
				'business_toll_free' => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[business_toll_free]',
					'title'     => 'Toll Free Phone',
					'desc'      => 'Your toll free number will be added to the top of the site.',
					'page_slug' => $page_slug,
					'section'   => 'contact_bar',
					'key'       => 'business_toll_free',
					'callback'  => 'sanitize_text_field',
				),
				'show_visa'          => array(
					'type'      => 'checkbox',
					'id'        => $option_name . '[show_visa]',
					'title'     => 'Show Visa?',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'contact_bar',
					'key'       => 'show_visa',
					'required'  => true,
					'callback'  => 'sanitize_check_box',
				),
				'show_mastercard'    => array(
					'type'      => 'checkbox',
					'id'        => $option_name . '[show_mastercard]',
					'title'     => 'Show MasterCard?',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'contact_bar',
					'key'       => 'show_mastercard',
					'required'  => true,
					'callback'  => 'sanitize_check_box',
				),
				'show_amex'          => array(
					'type'      => 'checkbox',
					'id'        => $option_name . '[show_amex]',
					'title'     => 'Show Amex?',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'contact_bar',
					'key'       => 'show_amex',
					'required'  => true,
					'callback'  => 'sanitize_check_box',
				),
				'show_dinersclub'    => array(
					'type'      => 'checkbox',
					'id'        => $option_name . '[show_dinersclub]',
					'title'     => 'Show Diners Club?',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'contact_bar',
					'key'       => 'show_dinersclub',
					'required'  => true,
					'callback'  => 'sanitize_check_box',
				),
				'media_url'    => array(
					'type'      => 'media',
					'id'        => $option_name . '[media_url]',
					'title'     => 'Upload Media',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'contact_bar',
					'key'       => 'media_url',
					'required'  => true,
					'callback'  => 'sanitize_check_box',
				),
			),
		),
		'footer_area' => array(
			'args'   => array(
				'id'        => 'footer_area',
				'title'     => 'Footer Area',
				'desc'      => 'Complete at least all required fields.',
				'page_slug' => $page_slug,
			),
			'fields' => array(
				'social_follow_text' => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[social_follow_text]',
					'title'     => 'Follow Us Text',
					'desc'      => 'This will update the "Follow Us" text in the footer.',
					'page_slug' => $page_slug,
					'section'   => 'footer_area',
					'key'       => 'social_follow_text',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'copyright_text'     => array(
					'type'      => 'editor',
					'id'        => $option_name . '[copyright_text]',
					'title'     => 'Copyright Text',
					'desc'      => 'This will update everything after "Copyright [date]" in the footer.',
					'page_slug' => $page_slug,
					'section'   => 'footer_area',
					'key'       => 'copyright_text',
					'required'  => true,
					'callback'  => 'wp_kses_post',
					'args'      => array(
//							'initial_content'  => 'initial content here',
						'settings' => array(
							'textarea_rows' => 3, // Default 10
							'wpautop'       => true, // Default true
							'media_buttons' => true, // Default true
							'tinymce'       => false,

						),
					),
				),
			),
		),
		'section_one' => array(
			'args'   => array(
				'id'        => 'section_business',
				'title'     => 'Business Information',
				'desc'      => 'Complete at least all required fields.',
				'page_slug' => $page_slug,
			),
			'fields' => array(
				'business_type' => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[business_type]',
					'title'     => 'Business Type',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_type',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),

				'business_name'    => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[business_name]',
					'title'     => 'Business Name',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_name',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_address' => array(
					'type'      => 'text_large',
					'id'        => $option_name . '[business_address]',
					'title'     => 'Business Address',
					'desc'      => 'ie: 123 Any St, Suite 101',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_address',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_city'    => array(
					'type'      => 'text_medium',
					'id'        => $option_name . '[business_city]',
					'title'     => 'City',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_city',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_state'   => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[business_state]',
					'title'     => 'State',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_state',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_zip'     => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[business_zip]',
					'title'     => 'Zip / Postal Code',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_zip',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_phone'   => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[business_phone]',
					'title'     => 'Phone',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_phone',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_fax'     => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[business_fax]',
					'title'     => 'Fax',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_fax',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_url'     => array(
					'type'      => 'text_medium',
					'id'        => $option_name . '[business_url]',
					'title'     => 'URL',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_url',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_desc'    => array(
					'type'      => 'text_area',
					'id'        => $option_name . '[business_desc]',
					'title'     => 'Business Description',
					'desc'      => 'Try and include some keywords in your business description.',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_desc',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),

				'areas_served' => array(
					'type'      => 'text_area',
					'id'        => $option_name . '[areas_served]',
					'title'     => 'Areas Served',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'areas_served',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),

				'business_glocal_url'     => array(
					'type'      => 'text_medium',
					'id'        => $option_name . '[business_glocal_url]',
					'title'     => 'Google Local Listing URL',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_glocal_url',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
				'business_directions_url' => array(
					'type'      => 'text_medium',
					'id'        => $option_name . '[business_directions_url]',
					'title'     => 'Directions URL',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'section_business',
					'key'       => 'business_directions_url',
					'required'  => true,
					'callback'  => 'sanitize_text_field',
				),
			), // end all fields
		), // end section one
		'section_two' => array(
			'args'   => array(
				'id'        => 'business_hours',
				'title'     => 'Business Hours',
				'desc'      => 'Fill out business hours like so: "9:00 am - 5:00 pm" OR "Closed", as the case may be.',
				'page_slug' => $page_slug,
			),
			'fields' => array(
				'hours_monday'    => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[hours_monday]',
					'title'     => 'Monday Hours',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'business_hours',
					'key'       => 'hours_monday',
					'required'  => false,
					'callback'  => 'sanitize_text_field',
				),
				'hours_tuesday'   => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[hours_tuesday]',
					'title'     => 'Tuesday Hours',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'business_hours',
					'key'       => 'hours_tuesday',
					'required'  => false,
					'callback'  => 'sanitize_text_field',
				),
				'hours_wednesday' => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[hours_wednesday]',
					'title'     => 'Wednesday Hours',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'business_hours',
					'key'       => 'hours_wednesday',
					'required'  => false,
					'callback'  => 'sanitize_text_field',
				),
				'hours_thursday'  => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[hours_thursday]',
					'title'     => 'Thursday Hours',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'business_hours',
					'key'       => 'hours_thursday',
					'required'  => false,
					'callback'  => 'sanitize_text_field',
				),
				'hours_friday'    => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[hours_friday]',
					'title'     => 'Friday Hours',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'business_hours',
					'key'       => 'hours_friday',
					'required'  => false,
					'callback'  => 'sanitize_text_field',
				),
				'hours_saturday'  => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[hours_saturday]',
					'title'     => 'Saturday Hours',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'business_hours',
					'key'       => 'hours_saturday',
					'required'  => false,
					'callback'  => 'sanitize_text_field',
				),
				'hours_sunday'    => array(
					'type'      => 'text_small',
					'id'        => $option_name . '[hours_sunday]',
					'title'     => 'Sunday Hours',
					'desc'      => '',
					'page_slug' => $page_slug,
					'section'   => 'business_hours',
					'key'       => 'hours_sunday',
					'required'  => false,
					'callback'  => 'sanitize_text_field',
				),
			), // end all fields
		), // End section two
	), // End metabox sections
); // end config array